name: Test

on:
  push:
    branches: [ master ]

jobs:
  merge:
    name: Merge master into private master
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Test
        run: |
          git status
          git checkout master
          git remote add privateRepo https://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@github.com/Ritesh-Ag/CICD-private.git
          git push publicRepo master