name: Test

on:
  push:
    branches: [ master ]

jobs:
  merge:
    name: Merge master into private master
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          git status
          git checkout master
          git remote add privateRepo https://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@github.com/Ritesh-Ag/CICD-private.git
          git push privateRepo master